# Generated by Django 4.0.2 on 2022-03-14 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.IntegerField(blank=True, choices=[(1, 'High'), (2, 'Medium'), (3, 'Low')], null=True)),
                ('title', models.CharField(max_length=50)),
                ('due_date', models.DateField(blank=True, default=None, null=True)),
                ('due_time', models.TimeField(blank=True, default=None, null=True)),
                ('notes', models.TextField(blank=True, help_text='Short notes', null=True)),
                ('completed', models.BooleanField(default=False)),
                ('completed_on', models.DateTimeField(blank=True, default=None, null=True)),
            ],
            options={
                'verbose_name': 'Task',
                'verbose_name_plural': 'Tasks',
                'ordering': ['priority', '-due_time', '-due_date', 'priority', 'title', 'completed_on'],
            },
        ),
    ]
